name: date_range_calendar
description: date_range_calendar helps your app can pick a range of dates.
version: 1.0.0
homepage: https://github.com/genbow3/flutter_date_range_calendar

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.6.4
  build_runner: ^2.13.1

flutter:
